"""empty message

Revision ID: 234df4ae0017
Revises: 7e4c8e54886a
Create Date: 2024-03-26 23:48:18.501095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '234df4ae0017'
down_revision: Union[str, None] = '7e4c8e54886a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('history', sa.Column('title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('history', 'title')
    # ### end Alembic commands ###
