"""empty message

Revision ID: ba43975e3ddd
Revises: d212ff457d12
Create Date: 2024-03-30 16:54:16.575064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba43975e3ddd'
down_revision: Union[str, None] = 'd212ff457d12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('history', sa.Column('total_unique_items_count', sa.Integer(), nullable=True))
    op.add_column('history', sa.Column('total_items_count', sa.Integer(), nullable=True))
    op.add_column('history', sa.Column('total_price', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('history', 'total_price')
    op.drop_column('history', 'total_items_count')
    op.drop_column('history', 'total_unique_items_count')
    # ### end Alembic commands ###
